# Generated by Django 4.2.1 on 2023-05-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccv_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ccv_vacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina_nome', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ccv_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeanimal', models.CharField(max_length=42)),
                ('raca', models.CharField(max_length=25)),
                ('dt_nascimento', models.DateTimeField()),
                ('idpessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ccv_pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ccv_agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_agenda', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(max_length=34)),
                ('idanimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ccv_animal')),
                ('idvacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ccv_vacinas')),
            ],
        ),
    ]
